# Generated by Django 3.0.8 on 2020-07-22 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoDatabase',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('todo_task', models.TextField(max_length=500)),
                ('slug', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
