# Generated by Django 3.0.8 on 2020-07-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododatabase',
            name='slug',
            field=models.IntegerField(),
        ),
    ]
